# Enable transparency
backend = "glx";
vsync = true;
opacity-rule = [
    "80:class_g = 'Lemonbar'",
    "82:class_g = 'dmenu'"
];

# rounded corners
corner-radius = 12

rounded-corners-exclude = [
  "class_g != 'dmenu'"
]

# Enable shadows
shadow = true;

animations = true;
animation-stiffness = 150.0;
animation-dampening = 20.0;
animation-clamping = true;
animation-mass = 1.0;
animation-for-workspace-switch-in = "slide-left";
animation-for-workspace-switch-out = "slide-right";
